name: Terraform

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-prod:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform (Prod)
        run: terraform init -backend-config=./environments/prod/backend-prod.tf

      - name: Terraform Plan (Prod)
        run: pwd
        run: terraform plan 

      - name: Terraform Apply (Prod)
        run: terraform apply --auto-approve

  terraform-dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform (Dev)
        run: terraform init -backend-config=./environments/dev/backend-dev.tf

      - name: Terraform Plan (Dev)
        run: pwd
        run: terraform plan 

      - name: Terraform Apply (Dev)
        run: terraform apply --auto-approve